# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/vivid32"

  config.vm.provision "file", source: "init/db/", destination: "db/"
  config.vm.provision "file", source: "init/vhosts/", destination: "vhosts/"

  config.vm.provision "shell", path: "init/initvm.sh"

  config.vm.synced_folder "../project", "/project"


  config.vm.network "private_network", ip: "192.168.20.21"

end
